/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package titans;

public class Library {
    protected static double[] arr = new double[31];

    private static int task2(int i, int j, double s){
        if(s <= arr[0]){
            return 0;
        }

        if(i == j - 1){
            return j;
        }

        if(arr[(i + j) / 2] >= s){
            return task2(i, (i + j) / 2, s);
        } else {
            return task2((i + j) / 2, j, s);
        }
    }

    public static void main(String[] args){
        arr[0] = 0;
        arr[1] = 2;
        arr[2] = 3;
        arr[14] = 14;
        System.out.println(task2(15, 31, 1));
    }
}
